# frozen_string_literal: true

module BrstBindingRubyGen
  # Emits Ruby source for the consolidated `types.rb` and per-file FFI modules.
  #
  # Generated layout:
  #   lib/brst/binding/ruby/types.rb        (all typedefs, enums, structs, consts)
  #   lib/brst/binding/ruby/<file>.rb        (functions for that .lsp file,
  #                                           plus a Sizes table for page_sizes.lsp)
  #
  # The four design improvements (per danbako 366):
  #   #1 Consolidated `:types` renderer (typedef'd from inner→outer mapping).
  #   #2 Enums emitted as FFI enums (effectively `:int`-backed typedefs).
  #   #3 Structs registered with `Struct.by_value` aliases for value semantics.
  #   #4 Every typedef lives in `types.rb`, so per-file modules have no
  #      load-order dependency on each other.
  module Renderer
    BANNER = <<~RB
      # frozen_string_literal: true
      #
      # AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
      # Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
      # DO NOT EDIT BY HAND. Re-generate with `rake generate`.
    RB

    module_function

    def module_name_from_filename(path)
      base = File.basename(path, ".lsp")
      camelize(base)
    end

    def camelize(s)
      s.to_s.split(/[_\-]/).map { |p| p[0]&.upcase.to_s + p[1..].to_s }.join
    end

    def snake_case(s)
      s.to_s
       .gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
       .gsub(/([a-z\d])([A-Z])/, '\1_\2')
       .downcase
    end

    # ---- types.rb -----------------------------------------------------------

    def render_types(symbols, lang: "en")
      out = +BANNER.dup
      out << <<~RB

        require "ffi"
        require_relative "library"

        module Brst
          module Binding
            module Ruby
              # Centralised type vocabulary for every generated FFI module.
              #
              # `Types.apply(mod)` registers every typedef, enum, and struct
              # alias on `mod` (which must already `extend FFI::Library`).
              # See generator/lib/brst_binding_ruby_gen/renderer.rb.
              module Types
                module_function

                # Each generated `<file>.rb` calls `Types.apply(self)` so that
                # all type symbols (`:Doc`, `:STATUS`, `:GMode`, ...) resolve
                # uniformly regardless of which .lsp file they originated in.
                def apply(mod)
                  return if mod.instance_variable_get(:@brst_types_applied)
                  mod.instance_variable_set(:@brst_types_applied, true)
                  apply_scalars(mod)
                  apply_pointers(mod)
                  apply_enums(mod)
                  apply_structs(mod)
                  apply_definitions(mod)
                end

                # ---- scalars (from types.lsp :types) ----
                def apply_scalars(mod)
      RB

      symbols.inner_to_ffi.each do |inner, ffi|
        next if inner == "void"
        next if inner.include?("*") # pointer-suffix variants are pointers
        out << "          mod.typedef #{ffi.inspect}, :#{ruby_type_sym(inner)}\n"
      end

      out << <<~RB
                end

                # ---- opaque pointers ----
                def apply_pointers(mod)
      RB
      symbols.pointers.each_key do |n|
        out << "          mod.typedef :pointer, :#{ruby_type_sym(n)}\n"
      end

      out << <<~RB
                end

                # ---- enums (improvement #2: each enum acts as an :int-backed typedef) ----
                def apply_enums(mod)
      RB
      symbols.enums.each_value do |enum_def|
        elements_src = enum_def[:elements].each_with_index.flat_map do |el, _i|
          v = el[:value]
          sym = symbol_literal(el[:element])
          if v.is_a?(Integer)
            [sym, v.to_s]
          else
            [sym]
          end
        end.join(", ")
        out << "          mod.enum #{symbol_literal(enum_def[:name])}, [#{elements_src}]\n"
      end

      out << <<~RB
                end

                # ---- structs (improvement #3: by_value alias) ----
                def apply_structs(mod)
      RB
      symbols.structs.each_value do |s|
        klass = struct_class_name(s[:name])
        out << "          unless mod.const_defined?(:#{klass}, false)\n"
        out << "            klass = Class.new(FFI::Struct) do\n"
        layout_pairs = s[:fields].map do |f|
          ":#{f[:field]}, #{symbols.resolve(f[:type]).inspect}"
        end
        out << "              layout #{layout_pairs.join(",\n                     ")}\n"
        out << "            end\n"
        out << "            mod.const_set(:#{klass}, klass)\n"
        out << "          end\n"
        out << "          mod.typedef mod.const_get(:#{klass}).by_value, :#{ruby_type_sym(s[:name])}\n"
      end

      out << <<~RB
                end

                # ---- definitions (typedef aliases) ----
                def apply_definitions(mod)
      RB
      symbols.definitions.each do |name, d|
        out << "          mod.typedef :#{ruby_type_sym(d[:original])}, :#{ruby_type_sym(name)}\n"
      end

      out << <<~RB
                end
              end
            end
          end
        end
      RB

      # Constants from consts.lsp — emitted as Ruby module constants under
      # Brst::Binding::Ruby::Const::BRST_<NAME>, mirroring libBeresta's BRST_
      # prefix convention.
      out << "\nmodule Brst\n  module Binding\n    module Ruby\n      module Const\n"
      symbols.consts.each_value do |c|
        next if c[:value].nil?
        literal = const_literal(c[:value])
        out << "        BRST_#{c[:name]} = #{literal}\n"
      end
      out << "      end\n    end\n  end\nend\n"

      # Page sizes from page_sizes.lsp — emitted as a frozen Hash so callers
      # can do width/height lookup without touching FFI.
      if !symbols.sizes.empty?
        out << "\nmodule Brst\n  module Binding\n    module Ruby\n      module PageSizesMM\n"
        out << "        TABLE = {\n"
        symbols.sizes.each do |s|
          out << "          #{s[:id].inspect} => { caption: #{s[:caption].inspect}, " \
                 "origin: #{s[:origin].inspect}, width_mm: #{s[:width]}, height_mm: #{s[:height]} },\n"
        end
        out << "        }.freeze\n"
        out << "      end\n    end\n  end\nend\n"
      end

      out
    end

    # ---- per-file modules ---------------------------------------------------

    def render_file(tree, symbols, lang: "en")
      file_name = tree[:file].to_s
      module_name = camelize(file_name.empty? ? "unknown" : file_name)

      functions = Array(tree[:functions])
      # Skip files that have only type declarations (already covered in types.rb)
      return nil if functions.empty? && Array(tree[:sizes]).empty?

      out = +BANNER.dup
      out << <<~RB

        require "ffi"
        require_relative "library"
        require_relative "types"

        module Brst
          module Binding
            module Ruby
              module #{module_name}
                extend FFI::Library
                ffi_lib Brst::Binding::Ruby::Library.lib_path

                Brst::Binding::Ruby::Types.apply(self)

                MISSING_SYMBOLS = []

                # Wraps `attach_function` so that captions whose actual C symbol
                # is missing from the loaded libBeresta build (e.g. caption /
                # symbol drift in upstream .lsp data, or features compiled
                # out) — or whose declared parameter types reference a struct
                # / enum the .lsp data never declared — don't break the entire
                # gem load. Each miss is recorded in MISSING_SYMBOLS for
                # diagnostic surfaces.
                def self.safe_attach(name, args, ret)
                  attach_function(name, args, ret)
                rescue FFI::NotFoundError, TypeError => e
                  MISSING_SYMBOLS << [name, e.message]
                end

      RB

      functions.each do |fn|
        next unless fn.is_a?(Hash)
        next if fn[:caption].nil?
        caption = fn[:caption].to_s
        param_types = Array(fn[:params]).map do |p|
          symbols.resolve(p[:type]).inspect
        end
        return_type = symbols.resolve(fn.dig(:result, :type)).inspect

        out << "          safe_attach :BRST_#{caption}, [#{param_types.join(', ')}], #{return_type}\n"
      end

      out << "      end\n    end\n  end\nend\n"
      out
    end

    # ---- helpers ------------------------------------------------------------

    def ruby_type_sym(name)
      name.to_s.tr("-", "_").gsub(/[^A-Za-z0-9_]/, "_")
    end

    # Return a Ruby source literal for a Symbol whose string contents may not
    # be a bare-identifier (e.g. starts with a digit, like "4A0"). Falls back
    # to the quoted-symbol form when needed.
    def symbol_literal(name)
      s = ruby_type_sym(name)
      if s =~ /\A[A-Za-z_][A-Za-z0-9_]*\z/
        ":#{s}"
      else
        ":\"#{s}\""
      end
    end

    def struct_class_name(name)
      camelize(name.to_s.tr("-", "_")) + "Struct"
    end

    def const_literal(v)
      case v
      when Integer
        v.to_s
      when Float
        v.to_s
      when String
        s = v.strip
        if s =~ /\A-?0x[0-9A-Fa-f]+\z/
          s
        elsif s =~ /\A-?\d+\z/
          s
        elsif s =~ /\A-?\d+\.\d+(?:[eE][+-]?\d+)?\z/
          s
        else
          s.inspect
        end
      else
        v.inspect
      end
    end
  end
end
