# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module Base
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Doc_New_Ex, [:pointer, :pointer, :pointer, :uint32, :pointer], :Doc
          safe_attach :BRST_Version, [], :string
          safe_attach :BRST_Doc_New, [:pointer, :pointer], :Doc
          safe_attach :BRST_Doc_New_Empty, [], :Doc
          safe_attach :BRST_Doc_Initialize, [:Doc], :uint32
          safe_attach :BRST_Doc_Destroy, [:Doc], :void
          safe_attach :BRST_Doc_Initialized, [:Doc], :int32
          safe_attach :BRST_Doc_Destroy_All, [:Doc], :void
          safe_attach :BRST_Doc_MMgr, [:Doc], :MMgr
          safe_attach :BRST_Doc_Free, [:Doc], :void
          safe_attach :BRST_PageSize_Width, [:PageSizes, :PageOrientation], :float
          safe_attach :BRST_PageSize_Height, [:PageSizes, :PageOrientation], :float
      end
    end
  end
end
