# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module Destination
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Destination_SetXYZ, [:Destination, :float, :float, :float], :uint32
          safe_attach :BRST_Destination_SetFit, [:Destination], :uint32
          safe_attach :BRST_Destination_SetFitH, [:Destination, :float], :uint32
          safe_attach :BRST_Destination_SetFitV, [:Destination, :float], :uint32
          safe_attach :BRST_Destination_SetFitR, [:Destination, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Destination_SetFitB, [:Destination], :uint32
          safe_attach :BRST_Destination_SetFitBH, [:Destination, :float], :uint32
          safe_attach :BRST_Destination_SetFitBV, [:Destination, :float], :uint32
      end
    end
  end
end
