# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module DocPage
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Doc_Pages_SetConfiguration, [:Doc, :uint32], :uint32
          safe_attach :BRST_Doc_Page_ByIndex, [:Doc, :uint32], :Page
          safe_attach :BRST_Doc_Page_Layout, [:Doc], :PageLayout
          safe_attach :BRST_Doc_Page_SetLayout, [:Doc, :PageLayout], :uint32
          safe_attach :BRST_Doc_Page_Mode, [:Doc], :PageMode
          safe_attach :BRST_Doc_Page_SetMode, [:Doc, :PageMode], :uint32
          safe_attach :BRST_Doc_Page_Current, [:Doc], :Page
          safe_attach :BRST_Doc_Page_Add, [:Doc], :Page
          safe_attach :BRST_Doc_Page_Insert, [:Doc, :Page], :Page
          safe_attach :BRST_Doc_Page_AddLabel, [:Doc, :uint32, :PageNumStyle, :uint32, :string], :uint32
      end
    end
  end
end
