# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module Geometry
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Page_GSave, [:Page], :uint32
          safe_attach :BRST_Page_GRestore, [:Page], :uint32
          safe_attach :BRST_Page_Concat, [:Page, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_Translate, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_Scale, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_RotateDeg, [:Page, :float], :uint32
          safe_attach :BRST_Page_Rotate, [:Page, :float], :uint32
          safe_attach :BRST_Page_Skew, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_Circle, [:Page, :float, :float, :float], :uint32
          safe_attach :BRST_Page_Ellipse, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_Arc, [:Page, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetGrayFill, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetGrayStroke, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetRGBFill, [:Page, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetRGBFillUint, [:Page, :uint8, :uint8, :uint8], :uint32
          safe_attach :BRST_Page_SetRGBFillHex, [:Page, :uint32], :uint32
          safe_attach :BRST_Page_SetRGBStroke, [:Page, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetRGBStrokeUint, [:Page, :uint8, :uint8, :uint8], :uint32
          safe_attach :BRST_Page_SetRGBStrokeHex, [:Page, :uint32], :uint32
          safe_attach :BRST_Page_SetCMYKFill, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetCMYKStroke, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_Clip, [:Page], :uint32
          safe_attach :BRST_Page_Eoclip, [:Page], :uint32
          safe_attach :BRST_Page_Stroke, [:Page], :uint32
          safe_attach :BRST_Page_ClosePathStroke, [:Page], :uint32
          safe_attach :BRST_Page_Fill, [:Page], :uint32
          safe_attach :BRST_Page_Eofill, [:Page], :uint32
          safe_attach :BRST_Page_FillStroke, [:Page], :uint32
          safe_attach :BRST_Page_EofillStroke, [:Page], :uint32
          safe_attach :BRST_Page_ClosePathFillStroke, [:Page], :uint32
          safe_attach :BRST_Page_ClosePathEofillStroke, [:Page], :uint32
          safe_attach :BRST_Page_EndPath, [:Page], :uint32
          safe_attach :BRST_Page_MoveTo, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_LineTo, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_CurveTo, [:Page, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_CurveTo2, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_CurveTo3, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_ClosePath, [:Page], :uint32
          safe_attach :BRST_Page_Rectangle, [:Page, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetLineWidth, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetLineCap, [:Page, :LineCap], :uint32
          safe_attach :BRST_Page_SetLineJoin, [:Page, :LineJoin], :uint32
          safe_attach :BRST_Page_SetMiterLimit, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetDash, [:Page, :pointer, :uint32, :float], :uint32
          safe_attach :BRST_Page_SetFlat, [:Page, :float], :uint32
          safe_attach :BRST_Page_GrayFill, [:Page], :float
          safe_attach :BRST_Page_GrayStroke, [:Page], :float
          safe_attach :BRST_Page_StrokeColorSpace, [:Page], :ColorSpace
          safe_attach :BRST_Page_FillColorSpace, [:Page], :ColorSpace
          safe_attach :BRST_Page_LineWidth, [:Page], :float
          safe_attach :BRST_Page_LineCap, [:Page], :LineCap
          safe_attach :BRST_Page_LineJoin, [:Page], :LineJoin
          safe_attach :BRST_Page_MiterLimit, [:Page], :float
          safe_attach :BRST_Page_Flat, [:Page], :float
          safe_attach :BRST_Page_Matrix, [:Page], :Matrix
      end
    end
  end
end
