# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module PageRoutines
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Page_SetWidth, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetHeight, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetBoundary, [:Page, :PageBoundary, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_SetSize, [:Page, :PageSizes, :PageOrientation], :uint32
          safe_attach :BRST_Page_SetRotate, [:Page, :uint16], :uint32
          safe_attach :BRST_Page_SetSlideShow, [:Page, :PageTransition, :float, :float], :uint32
          safe_attach :BRST_Page_SetHorizontalScaling, [:Page, :float], :uint32
          safe_attach :BRST_Page_GStateDepth, [:Page], :uint32
          safe_attach :BRST_Page_HorizontalScaling, [:Page], :float
          safe_attach :BRST_Page_SetZoom, [:Page, :float], :uint32
          safe_attach :BRST_Page_Width, [:Page], :float
          safe_attach :BRST_Page_Height, [:Page], :float
          safe_attach :BRST_Page_GMode, [:Page], :uint16
          safe_attach :BRST_Page_MMgr, [:Page], :MMgr
          safe_attach :BRST_Page_Insert_Shared_Content_Stream, [:Page, :Dict], :uint32
          safe_attach :BRST_Page_RawWrite, [:Page, :string], :uint32
          safe_attach :BRST_Page_SetExtGState, [:Page, :ExtGState], :uint32
          safe_attach :BRST_Page_CreateDestination, [:Page], :Destination
      end
    end
  end
end
