# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module StreamText
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Stream_BeginText, [:Stream], :uint32
          safe_attach :BRST_Stream_EndText, [:Stream], :uint32
          safe_attach :BRST_Stream_SetTextLeading, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_SetTextRenderingMode, [:Stream, :TextRenderingMode], :uint32
          safe_attach :BRST_Stream_MoveTextPos, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_MoveTextPos2, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_SetTextMatrix, [:Stream, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_ShowText, [:Stream, :Font, :string], :uint32
          safe_attach :BRST_Stream_TextOut, [:Stream, :Font, :float, :float, :string], :uint32
          safe_attach :BRST_Stream_MoveToNextLine, [:Stream], :uint32
      end
    end
  end
end
