# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module StreamGeometry
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Stream_GSave, [:Stream], :uint32
          safe_attach :BRST_Stream_GRestore, [:Stream], :uint32
          safe_attach :BRST_Stream_Concat, [:Stream, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_Translate, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_Scale, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_RotateDeg, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_Rotate, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_Skew, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_Circle, [:Stream, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_SetGrayFill, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_SetGrayStroke, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_SetRGBFill, [:Stream, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_SetRGBFillUint, [:Stream, :uint8, :uint8, :uint8], :uint32
          safe_attach :BRST_Stream_SetRGBFillHex, [:Stream, :uint32], :uint32
          safe_attach :BRST_Stream_SetRGBStroke, [:Stream, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_SetRGBStrokeUint, [:Stream, :uint8, :uint8, :uint8], :uint32
          safe_attach :BRST_Stream_SetRGBStrokeHex, [:Stream, :uint32], :uint32
          safe_attach :BRST_Stream_SetCMYKFill, [:Stream, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_SetCMYKStroke, [:Stream, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_Clip, [:Stream], :uint32
          safe_attach :BRST_Stream_Eoclip, [:Stream], :uint32
          safe_attach :BRST_Stream_Stroke, [:Stream], :uint32
          safe_attach :BRST_Stream_ClosePathStroke, [:Stream], :uint32
          safe_attach :BRST_Stream_Fill, [:Stream], :uint32
          safe_attach :BRST_Stream_Eofill, [:Stream], :uint32
          safe_attach :BRST_Stream_FillStroke, [:Stream], :uint32
          safe_attach :BRST_Stream_EofillStroke, [:Stream], :uint32
          safe_attach :BRST_Stream_ClosePathFillStroke, [:Stream], :uint32
          safe_attach :BRST_Stream_ClosePathEofillStroke, [:Stream], :uint32
          safe_attach :BRST_Stream_EndPath, [:Stream], :uint32
          safe_attach :BRST_Stream_MoveTo, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_LineTo, [:Stream, :float, :float], :uint32
          safe_attach :BRST_Stream_CurveTo, [:Stream, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_CurveTo2, [:Stream, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_CurveTo3, [:Stream, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_ClosePath, [:Stream], :uint32
          safe_attach :BRST_Stream_Rectangle, [:Stream, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Stream_SetLineWidth, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_SetLineCap, [:Stream, :LineCap], :uint32
          safe_attach :BRST_Stream_SetLineJoin, [:Stream, :LineJoin], :uint32
          safe_attach :BRST_Stream_SetMiterLimit, [:Stream, :float], :uint32
          safe_attach :BRST_Stream_SetDash, [:Stream, :pointer, :uint32, :float], :uint32
          safe_attach :BRST_Stream_SetFlat, [:Stream, :float], :uint32
      end
    end
  end
end
