# frozen_string_literal: true
#
# AUTO-GENERATED by brst-binding-ruby's generator (generator/bin/brst-binding-ruby-gen).
# Source of truth: libBeresta gen/data/*.lsp (S-expression definitions).
# DO NOT EDIT BY HAND. Re-generate with `rake generate`.

require "ffi"
require_relative "library"
require_relative "types"

module Brst
  module Binding
    module Ruby
      module Text
        extend FFI::Library
        ffi_lib Brst::Binding::Ruby::Library.lib_path

        Brst::Binding::Ruby::Types.apply(self)

        MISSING_SYMBOLS = []

        # Wraps `attach_function` so that captions whose actual C symbol
        # is missing from the loaded libBeresta build (e.g. caption /
        # symbol drift in upstream .lsp data, or features compiled
        # out) — or whose declared parameter types reference a struct
        # / enum the .lsp data never declared — don't break the entire
        # gem load. Each miss is recorded in MISSING_SYMBOLS for
        # diagnostic surfaces.
        def self.safe_attach(name, args, ret)
          attach_function(name, args, ret)
        rescue FFI::NotFoundError, TypeError => e
          MISSING_SYMBOLS << [name, e.message]
        end

          safe_attach :BRST_Page_BeginText, [:Page], :uint32
          safe_attach :BRST_Page_EndText, [:Page], :uint32
          safe_attach :BRST_Page_SetTextLeading, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetFontAndSize, [:Page, :Font, :float], :uint32
          safe_attach :BRST_Dict_SetFontAndSize, [:Dict, :Font, :float], :uint32
          safe_attach :BRST_Page_SetTextRenderingMode, [:Page, :TextRenderingMode], :uint32
          safe_attach :BRST_Page_SetTextRise, [:Page, :float], :uint32
          safe_attach :BRST_Page_MoveTextPos, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_MoveTextPos2, [:Page, :float, :float], :uint32
          safe_attach :BRST_Page_SetTextMatrix, [:Page, :float, :float, :float, :float, :float, :float], :uint32
          safe_attach :BRST_Page_MoveToNextLine, [:Page], :uint32
          safe_attach :BRST_Page_ShowText, [:Page, :string], :uint32
          safe_attach :BRST_Page_ShowTextNextLine, [:Page, :string], :uint32
          safe_attach :BRST_Page_ShowTextNextLineEx, [:Page, :float, :float, :string], :uint32
          safe_attach :BRST_Page_TextOut, [:Page, :float, :float, :string], :uint32
          safe_attach :BRST_Page_TextRect, [:Page, :float, :float, :float, :float, :string, :TextAlignment, :pointer], :uint32
          safe_attach :BRST_Page_SetCharSpace, [:Page, :float], :uint32
          safe_attach :BRST_Page_SetWordSpace, [:Page, :float], :uint32
          safe_attach :BRST_Page_TextMatrix, [:Page], :Matrix
          safe_attach :BRST_Page_TextLeading, [:Page], :float
          safe_attach :BRST_Page_TextRenderingMode, [:Page], :TextRenderingMode
          safe_attach :BRST_Page_TextRise, [:Page], :float
          safe_attach :BRST_Page_CharSpace, [:Page], :float
          safe_attach :BRST_Page_WordSpace, [:Page], :float
          safe_attach :BRST_Page_CurrentTextPos2, [:Page, :pointer], :uint32
          safe_attach :BRST_Page_CurrentFont, [:Page], :Font
          safe_attach :BRST_Page_CurrentFontSize, [:Page], :float
          safe_attach :BRST_Page_TextWidth, [:Page, :string], :float
          safe_attach :BRST_Page_MeasureText, [:Page, :string, :float, :int32, :pointer], :uint32
      end
    end
  end
end
